import React,{useState,useEffect} from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Cd from "@/components/Cd";
import AirSelector from "@/components/AirSelector";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function AirPage() {
  const [city, setCity] = useState("");
  const [air, setAir] = useState("济南");
  const [airp, setAirp] = useState("济南");
  
  function handleWeatherChange(newCity) {
    setCity(newCity);
  }
  function handleAirChange(newAir) {
    setAir(newAir);
  }
  function handleAirpChange(newAirp){
    setAirp(newAirp);
  }
  return (
    <>
      <Head>
        <title>Air Now!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Air Now &nbsp;
            <code className={styles.code}>呼吸!</code>
          </p>
          <div>
            <AirSelector onWeatherChange={handleWeatherChange} onAirChange={handleAirChange} onAirpChange={handleAirpChange}/>
          </div>
        </div>

        <div className={styles.center}>
          <h1 className={styles.title}>Breath in {city}!</h1>
        </div>
          <div className={styles.grid}>
            <div className={styles.card}>
              <h2 className={inter.className}>空调:{air.brief}</h2>
              <p className={inter.className}>
                <code className={styles.code}>{air.details}</code>
              </p>
            </div>
            <div className={styles.card}>
              <h2 className={inter.className}>空气:{airp.brief}</h2>
              <p className={inter.className}>
                <code className={styles.code}>{airp.details}</code>
              </p>
            </div>
            <div className={styles.card}>
              <h2 className={inter.className}>空气</h2>
              <p className={inter.className}>
                <code className={styles.code}>Air Now!</code>
              </p>
            </div>
            <div className={styles.card}>
              <h2 className={inter.className}>空气</h2>
              <p className={inter.className}>
                <code className={styles.code}>Air Now!</code>
              </p>
            </div>
            <div className={styles.card}>
              <h2 className={inter.className}>空气</h2>
              <p className={inter.className}>
                <code className={styles.code}>Air Now!</code>
              </p>
            </div>
            <div className={styles.card}>
              <h2 className={inter.className}>空气</h2>
              <p className={inter.className}>
                <code className={styles.code}>Air Now!</code>
              </p>
            </div>
            <div className={styles.card}>
              <h2 className={inter.className}>空气</h2>
              <p className={inter.className}>
                <code className={styles.code}>Air Now!</code>
              </p>
            </div>
            <div className={styles.card}>
              <h2 className={inter.className}>一目了然?</h2>
              <p className={inter.className}>
                <code className={styles.code}>Breath!</code>
              </p>
            </div>
          </div>

        <Cd />
      </main>
    </>
  );
}
