import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import axios from "axios";
import { useState, useEffect } from "react";
//引入组件
import Footer from "@/components/Footer";
import WeatherSelector from "@/components/Weather/WeatherSelector";
import WeatherLogo from "@/components/Weather/WeatherLogo";
import Air from "@/components/Air/Air";
import Trad from "@/components/Tradition/Trad";
import Four from "@/components/Forecast/Four";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [city, setCity] = useState("济南");
  const [weather, setWeather] = useState({});
  //空气质量
  const [air, setAir] = useState("济南");

  //发送axios请求,主页天气数据
  useEffect(() => {
    axios
      .get(
        `https://api.seniverse.com/v3/weather/now.json?key=SjPJO8uWbDNjYyU4i&location=${city}&language=zh-Hans&unit=c`
      )
      .then((res) => {
        //将获取数据渲染
        setWeather(res.data.results[0].now);
      });
    axios
      .get(
        `https://api.seniverse.com/v3/air/now.json?key=SIKgGG7jSVrpD4Zb4&location=${city}&language=zh-Hans&scope=city`
      )
      .then((res) => {
        //将获取数据渲染
        setAir(res.data.results[0].air.city);
      });
  }, [city]);

  function handleWeatherChange(newWeather, newCity) {
    setWeather(newWeather);
    setCity(newCity);
  }

  return (
    <>
      <Head>
        <title>Weather Now!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Welcome to &nbsp;
            <code className={styles.code}>Weather Now!</code>
          </p>
          <div>
            <WeatherSelector onWeatherChange={handleWeatherChange} />
          </div>
        </div>

        <div className={styles.center}>
          <WeatherLogo city={city} />
          <h1 className={styles.title}>{city}</h1>
          <h2>
            {weather.text} {weather.temperature}°C
          </h2>
        </div>

        <div className={styles.grid}>
          <Air city={city} />
          <Trad />

          <a
            href="/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              日月 <span>-&gt;</span>
            </h2>
            <p className={inter.className}>日出而华灯初上，日落而花好月圆
            别点我，开发中😜...
            </p>
          </a>

          <Four city={city}/>
        </div>
        <Footer />
      </main>
    </>
  );
}
