import React, { useState, useEffect } from "react";
import { Space, Table, Tag } from "antd";
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Cd from "@/components/Cd";
import axios from "axios";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });

export default function Tradition() {
  const [dataa, setDataa] = useState([]);
  const columns = [
    {
      title: "",
      dataIndex: "",
      key: "",
    },
    {
      title: "日期",
      dataIndex: "date",
      key: "date",
    },
    {
      title: "干支月",
      dataIndex: "ganzhi_month",
      key: "ganzhi_month",
    },
    {
      title: "干支日",
      dataIndex: "ganzhi_day",
      key: "ganzhi_day",
    },
    {
      title: "农历月",
      dataIndex: "lunar_month_name",
      key: "lunar_month_name",
    },
    {
      title: "农历日",
      key: "lunar_day_name",
      dataIndex: "lunar_day_name",
    },
    {
      title: "节气",
      key: "solar_term",
      dataIndex: "solar_term",
      //判断是否有节气，如果有让字体变红
      render: (_, { solar_term }) => (
        <>
          {solar_term ? (
            <Tag color="green" key={solar_term}>
              {solar_term}
            </Tag>
          ) : (
            <Tag color="green" key={solar_term}>
              {solar_term}
            </Tag>
          )}
        </>
      ),
    },
    {
      title: "",
      dataIndex: "",
      key: "",
    },
  ];
  useEffect(() => {
    const interval = setInterval(() => {
      axios
        .get(
          `https://api.seniverse.com/v3/life/chinese_calendar.json?key=SIKgGG7jSVrpD4Zb4&start=0&days=7`
        )
        .then((res) => {
          setDataa(res.data.results.chinese_calendar);
        });
    }, 500);
    return () => clearInterval(interval);
  }, []);

  return (
    <>
      <Head>
        <title>Tradition Now!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            传统 &nbsp;
            <code className={styles.code}>历法</code>
          </p>
        </div>

        <div className={styles.center}>
          {/* <h1 className={styles.title}>Breath in!</h1> */}
          <Table columns={columns} dataSource={dataa} pagination={false} />
        </div>

        <Cd />
        <Footer/>
      </main>
    </>
  );
}
